DECLARE
  V_SQL VARCHAR2(2000);
  V_I   INT := 0;
BEGIN
  DBMS_OUTPUT.PUT_LINE(1 / V_I);
  EXECUTE IMMEDIATE 'insert t_001 select * from dual';
  DBMS_OUTPUT.PUT_LINE('中文+123abd');
EXCEPTION
  WHEN OTHERS THEN
    DBMS_OUTPUT.PUT_LINE(SQLCODE);
END;
/
